version: "3"

services:
  application:
    image: springboot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/sbms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Swain@123
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - springboot-db-net

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Swain@123
      MYSQL_DATABASE: sbms
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-db-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  springboot-db-net:

volumes:
  mysql_data:

