spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/sbms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Swain@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

